//Source code generated by AppGPT (www.appgpt.tech)

//Class to create tables and seed new database
import { DataSource } from 'typeorm';
import { DBConfiguration } from './Configuration';
import { SettingsEntity } from './db/Settings.entity';
//autogenerate imports based on resources
import { UsersEntity } from './db/Users.entity';
import { VendorsEntity } from './db/Vendors.entity';
import { CustomersEntity } from './db/Customers.entity';
import { InventoryEntity } from './db/Inventory.entity';
import { ProductsEntity } from './db/Products.entity';
import { ProductCategoriesEntity } from './db/ProductCategories.entity';
import { DiscountsEntity } from './db/Discounts.entity';
import { ShoppingCartEntity } from './db/ShoppingCart.entity';
import { OrdersEntity } from './db/Orders.entity';
import { OrderDetailsEntity } from './db/OrderDetails.entity';
import { PaymentsEntity } from './db/Payments.entity';
import { ReviewsEntity } from './db/Reviews.entity';
import { SupportTicketsEntity } from './db/SupportTickets.entity';

export class Database {
  static dbConfiguration: DBConfiguration;
  public static ds: DataSource;

  static async Initialize(dbConfiguration: DBConfiguration) {
    Database.dbConfiguration = dbConfiguration;
    let dbConfig: any = dbConfiguration as any;
    //Autogenerate entities array from resource names

    dbConfig.entities = [
      SettingsEntity,
      UsersEntity,
      VendorsEntity,
      CustomersEntity,
      InventoryEntity,
      ProductsEntity,
      ProductCategoriesEntity,
      DiscountsEntity,
      ShoppingCartEntity,
      OrdersEntity,
      OrderDetailsEntity,
      PaymentsEntity,
      ReviewsEntity,
      SupportTicketsEntity,
    ];
    Database.ds = new DataSource(dbConfig);
    await Database.ds.initialize();

    //TODO: Drop all tables

    await Database.Seed();
  }
  static async Seed() {
    let data: any = {
      Users: [
        {
          username: 'username 1',
          email: 'email 1',
          password: 'password 1',
          role: 'role 1',
          id: 13,
        },
        {
          username: 'username 2',
          email: 'email 2',
          password: 'password 2',
          role: 'role 2',
          id: 26,
        },
        {
          username: 'username 3',
          email: 'email 3',
          password: 'password 3',
          role: 'role 3',
          id: 68,
        },
        {
          username: 'username 4',
          email: 'email 4',
          password: 'password 4',
          role: 'role 4',
          id: 18,
        },
        {
          username: 'username 5',
          email: 'email 5',
          password: 'password 5',
          role: 'role 5',
          id: 13,
        },
      ],
      Vendors: [
        {
          companyName: 'companyName 1',
          contactName: 'contactName 1',
          email: 'email 1',
          password: 'password 1',
          id: 72,
        },
        {
          companyName: 'companyName 2',
          contactName: 'contactName 2',
          email: 'email 2',
          password: 'password 2',
          id: 60,
        },
        {
          companyName: 'companyName 3',
          contactName: 'contactName 3',
          email: 'email 3',
          password: 'password 3',
          id: 19,
        },
        {
          companyName: 'companyName 4',
          contactName: 'contactName 4',
          email: 'email 4',
          password: 'password 4',
          id: 45,
        },
        {
          companyName: 'companyName 5',
          contactName: 'contactName 5',
          email: 'email 5',
          password: 'password 5',
          id: 34,
        },
      ],
      Customers: [
        {
          customerName: 'customerName 1',
          email: 'email 1',
          password: 'password 1',
          billingAddress: 'billingAddress 1',
          shippingAddress: 'shippingAddress 1',
          country: 'country 1',
          phone: 'phone 1',
          id: 49,
        },
        {
          customerName: 'customerName 2',
          email: 'email 2',
          password: 'password 2',
          billingAddress: 'billingAddress 2',
          shippingAddress: 'shippingAddress 2',
          country: 'country 2',
          phone: 'phone 2',
          id: 67,
        },
        {
          customerName: 'customerName 3',
          email: 'email 3',
          password: 'password 3',
          billingAddress: 'billingAddress 3',
          shippingAddress: 'shippingAddress 3',
          country: 'country 3',
          phone: 'phone 3',
          id: 87,
        },
        {
          customerName: 'customerName 4',
          email: 'email 4',
          password: 'password 4',
          billingAddress: 'billingAddress 4',
          shippingAddress: 'shippingAddress 4',
          country: 'country 4',
          phone: 'phone 4',
          id: 68,
        },
        {
          customerName: 'customerName 5',
          email: 'email 5',
          password: 'password 5',
          billingAddress: 'billingAddress 5',
          shippingAddress: 'shippingAddress 5',
          country: 'country 5',
          phone: 'phone 5',
          id: 42,
        },
      ],
      Inventory: [
        { product: 1, quantity: 1, lowStockThreshold: 1, id: 51 },
        { product: 2, quantity: 2, lowStockThreshold: 2, id: 84 },
        { product: 3, quantity: 3, lowStockThreshold: 3, id: 22 },
        { product: 4, quantity: 4, lowStockThreshold: 4, id: 84 },
        { product: 5, quantity: 5, lowStockThreshold: 5, id: 29 },
      ],
      Products: [
        {
          productName: 'productName 1',
          vendor: 1,
          price: 0.79,
          weight: 0.83,
          description: 'description 1',
          thumbnail: 'thumbnail 1',
          image: 'image 1',
          category: 1,
          creationDate: '2024-07-11T06:06:55.615Z',
          stock: 1,
          id: 55,
        },
        {
          productName: 'productName 2',
          vendor: 2,
          price: 0.12,
          weight: 0.65,
          description: 'description 2',
          thumbnail: 'thumbnail 2',
          image: 'image 2',
          category: 2,
          creationDate: '2024-01-18T19:45:36.237Z',
          stock: 2,
          id: 37,
        },
        {
          productName: 'productName 3',
          vendor: 3,
          price: 0.5,
          weight: 0.67,
          description: 'description 3',
          thumbnail: 'thumbnail 3',
          image: 'image 3',
          category: 3,
          creationDate: '2024-10-14T11:10:38.023Z',
          stock: 3,
          id: 14,
        },
        {
          productName: 'productName 4',
          vendor: 4,
          price: 0.17,
          weight: 0.34,
          description: 'description 4',
          thumbnail: 'thumbnail 4',
          image: 'image 4',
          category: 4,
          creationDate: '2024-05-07T13:43:56.135Z',
          stock: 4,
          id: 48,
        },
        {
          productName: 'productName 5',
          vendor: 5,
          price: 0.1,
          weight: 0.75,
          description: 'description 5',
          thumbnail: 'thumbnail 5',
          image: 'image 5',
          category: 5,
          creationDate: '2023-12-13T04:47:07.878Z',
          stock: 5,
          id: 64,
        },
      ],
      ProductCategories: [
        { category: 'category 1', id: 69 },
        { category: 'category 2', id: 67 },
        { category: 'category 3', id: 81 },
        { category: 'category 4', id: 85 },
        { category: 'category 5', id: 37 },
      ],
      Discounts: [
        {
          product: 1,
          discountType: 'discountType 1',
          description: 'description 1',
          discountAmount: 0.7,
          discountPercent: 0.31,
          id: 37,
        },
        {
          product: 2,
          discountType: 'discountType 2',
          description: 'description 2',
          discountAmount: 0.29,
          discountPercent: 0.24,
          id: 23,
        },
        {
          product: 3,
          discountType: 'discountType 3',
          description: 'description 3',
          discountAmount: 0.7,
          discountPercent: 0.27,
          id: 45,
        },
        {
          product: 4,
          discountType: 'discountType 4',
          description: 'description 4',
          discountAmount: 1,
          discountPercent: 0.57,
          id: 45,
        },
        {
          product: 5,
          discountType: 'discountType 5',
          description: 'description 5',
          discountAmount: 0.48,
          discountPercent: 0.09,
          id: 60,
        },
      ],
      ShoppingCart: [
        { customer: 1, product: 1, priceAtPurchase: 0.87, quantity: 1, id: 41 },
        { customer: 2, product: 2, priceAtPurchase: 0.61, quantity: 2, id: 23 },
        { customer: 3, product: 3, priceAtPurchase: 0.57, quantity: 3, id: 37 },
        { customer: 4, product: 4, priceAtPurchase: 0.53, quantity: 4, id: 42 },
        { customer: 5, product: 5, priceAtPurchase: 0.35, quantity: 5, id: 44 },
      ],
      Orders: [
        {
          orderNumber: 'orderNumber 1',
          customer: 1,
          totalAmount: 0.74,
          vat: 0.52,
          totalAmountWithVat: 0.98,
          shippingCost: 0.82,
          shippingAddress: 'shippingAddress 1',
          orderAddress: 'orderAddress 1',
          orderEmail: 'orderEmail 1',
          orderDate: '2024-03-10T04:38:05.393Z',
          orderStatus: 'orderStatus 1',
          trackingNo: 'trackingNo 1',
          id: 92,
        },
        {
          orderNumber: 'orderNumber 2',
          customer: 2,
          totalAmount: 0.82,
          vat: 0.86,
          totalAmountWithVat: 0.49,
          shippingCost: 0.38,
          shippingAddress: 'shippingAddress 2',
          orderAddress: 'orderAddress 2',
          orderEmail: 'orderEmail 2',
          orderDate: '2024-09-02T16:47:10.152Z',
          orderStatus: 'orderStatus 2',
          trackingNo: 'trackingNo 2',
          id: 93,
        },
        {
          orderNumber: 'orderNumber 3',
          customer: 3,
          totalAmount: 0.05,
          vat: 0.64,
          totalAmountWithVat: 0.78,
          shippingCost: 0.25,
          shippingAddress: 'shippingAddress 3',
          orderAddress: 'orderAddress 3',
          orderEmail: 'orderEmail 3',
          orderDate: '2023-05-06T11:50:09.338Z',
          orderStatus: 'orderStatus 3',
          trackingNo: 'trackingNo 3',
          id: 12,
        },
        {
          orderNumber: 'orderNumber 4',
          customer: 4,
          totalAmount: 0.24,
          vat: 0.41,
          totalAmountWithVat: 0.3,
          shippingCost: 0.26,
          shippingAddress: 'shippingAddress 4',
          orderAddress: 'orderAddress 4',
          orderEmail: 'orderEmail 4',
          orderDate: '2023-07-30T22:49:48.373Z',
          orderStatus: 'orderStatus 4',
          trackingNo: 'trackingNo 4',
          id: 23,
        },
        {
          orderNumber: 'orderNumber 5',
          customer: 5,
          totalAmount: 0.49,
          vat: 0.47,
          totalAmountWithVat: 0.4,
          shippingCost: 0.85,
          shippingAddress: 'shippingAddress 5',
          orderAddress: 'orderAddress 5',
          orderEmail: 'orderEmail 5',
          orderDate: '2023-06-26T04:13:41.416Z',
          orderStatus: 'orderStatus 5',
          trackingNo: 'trackingNo 5',
          id: 45,
        },
      ],
      OrderDetails: [
        { orderNumber: 1, line: 1, product: 1, price: 1, quantity: 1, id: 32 },
        {
          orderNumber: 2,
          line: 2,
          product: 2,
          price: 0.36,
          quantity: 2,
          id: 3,
        },
        {
          orderNumber: 3,
          line: 3,
          product: 3,
          price: 0.22,
          quantity: 3,
          id: 31,
        },
        {
          orderNumber: 4,
          line: 4,
          product: 4,
          price: 0.44,
          quantity: 4,
          id: 81,
        },
        {
          orderNumber: 5,
          line: 5,
          product: 5,
          price: 0.37,
          quantity: 5,
          id: 20,
        },
      ],
      Payments: [
        {
          orderNumber: 1,
          amount: 0.12,
          paymentMethod: 'paymentMethod 1',
          paymentDate: '2024-12-26T16:55:05.743Z',
          paymentStatus: 'paymentStatus 1',
          id: 29,
        },
        {
          orderNumber: 2,
          amount: 0.38,
          paymentMethod: 'paymentMethod 2',
          paymentDate: '2025-04-03T04:32:36.355Z',
          paymentStatus: 'paymentStatus 2',
          id: 45,
        },
        {
          orderNumber: 3,
          amount: 0.88,
          paymentMethod: 'paymentMethod 3',
          paymentDate: '2025-02-07T02:20:38.658Z',
          paymentStatus: 'paymentStatus 3',
          id: 47,
        },
        {
          orderNumber: 4,
          amount: 0.68,
          paymentMethod: 'paymentMethod 4',
          paymentDate: '2023-07-16T12:56:21.643Z',
          paymentStatus: 'paymentStatus 4',
          id: 57,
        },
        {
          orderNumber: 5,
          amount: 0.37,
          paymentMethod: 'paymentMethod 5',
          paymentDate: '2024-06-14T08:03:32.766Z',
          paymentStatus: 'paymentStatus 5',
          id: 22,
        },
      ],
      Reviews: [
        {
          product: 1,
          customer: 1,
          vendor: 1,
          rating: 0.73,
          reviewDetails: 'reviewDetails 1',
          date: '2024-08-21T21:17:09.723Z',
          id: 40,
        },
        {
          product: 2,
          customer: 2,
          vendor: 2,
          rating: 0.89,
          reviewDetails: 'reviewDetails 2',
          date: '2023-08-22T11:08:07.965Z',
          id: 61,
        },
        {
          product: 3,
          customer: 3,
          vendor: 3,
          rating: 0.71,
          reviewDetails: 'reviewDetails 3',
          date: '2023-07-13T07:15:02.024Z',
          id: 76,
        },
        {
          product: 4,
          customer: 4,
          vendor: 4,
          rating: 0.21,
          reviewDetails: 'reviewDetails 4',
          date: '2023-06-09T23:40:02.960Z',
          id: 0,
        },
        {
          product: 5,
          customer: 5,
          vendor: 5,
          rating: 0.34,
          reviewDetails: 'reviewDetails 5',
          date: '2023-08-17T20:24:46.205Z',
          id: 13,
        },
      ],
      SupportTickets: [
        {
          user: 1,
          customer: 1,
          description: 'description 1',
          status: 'status 1',
          creationDate: '2024-11-14T10:11:34.142Z',
          resolutionDate: '2025-03-21T05:21:53.963Z',
          id: 19,
        },
        {
          user: 2,
          customer: 2,
          description: 'description 2',
          status: 'status 2',
          creationDate: '2023-05-08T10:25:28.213Z',
          resolutionDate: '2024-09-09T16:42:04.939Z',
          id: 87,
        },
        {
          user: 3,
          customer: 3,
          description: 'description 3',
          status: 'status 3',
          creationDate: '2024-06-09T06:27:35.082Z',
          resolutionDate: '2024-04-08T19:29:02.258Z',
          id: 91,
        },
        {
          user: 4,
          customer: 4,
          description: 'description 4',
          status: 'status 4',
          creationDate: '2024-10-05T09:51:52.605Z',
          resolutionDate: '2024-11-03T02:06:47.996Z',
          id: 96,
        },
        {
          user: 5,
          customer: 5,
          description: 'description 5',
          status: 'status 5',
          creationDate: '2023-05-12T16:30:54.830Z',
          resolutionDate: '2023-10-18T11:17:42.224Z',
          id: 71,
        },
      ],
    };
    //Autogenerate multiple such calls ie for each resource and its data object
    let isSeeded = await this.IsSeeded();
    //if (!isSeeded) {
    //forcing app recreation
    if (true) {
      console.log('   Seeding database...');
      await this.SeedResource('UsersEntity', data.Users);
      await this.SeedResource('VendorsEntity', data.Vendors);
      await this.SeedResource('CustomersEntity', data.Customers);
      await this.SeedResource('InventoryEntity', data.Inventory);
      await this.SeedResource('ProductsEntity', data.Products);
      await this.SeedResource(
        'ProductCategoriesEntity',
        data.ProductCategories,
      );
      await this.SeedResource('DiscountsEntity', data.Discounts);
      await this.SeedResource('ShoppingCartEntity', data.ShoppingCart);
      await this.SeedResource('OrdersEntity', data.Orders);
      await this.SeedResource('OrderDetailsEntity', data.OrderDetails);
      await this.SeedResource('PaymentsEntity', data.Payments);
      await this.SeedResource('ReviewsEntity', data.Reviews);
      await this.SeedResource('SupportTicketsEntity', data.SupportTickets);
      await this.SeedResource('SettingsEntity', {
        settingname: 'isSeeded',
        settingvalue: 'true',
      });
    } else {
      console.log('   Database seeded already!');
    }
  }
  static async IsSeeded() {
    const repo = Database.ds.getRepository('SettingsEntity');
    let rec: any = await repo.findOne({
      select: {
        settingname: true,
        settingvalue: true,
      },
      where: {
        settingname: 'isSeeded',
      },
    });
    if (rec && rec.settingvalue) return true;
    return false;
  }
  static async SeedResource(resourceName: any, resourceData: any) {
    const repo = Database.ds.getRepository(resourceName);
    //await repo.clear();
    console.log('   Seeding table ' + resourceName);
    await repo.upsert(resourceData, ['id']);
  }
}
